### ISSUE TITLE
Any chance for a new release to fix the name drift on precompiled assets?

### ISSUE THREAD

**Issue by amokan** [elixir-nx/hnswlib#4]
Looks like the project was renamed from `hnswlib_elixir` to `hnswlib` in [this commit](https://github.com/elixir-nx/hnswlib/commit/ce5a3a37e341ca7953c333bb335aa2666337af7f).

It would be awesome if someone could kick the tires on a new release just so the precompiled versions on github could be utilized. Unfortunately the [precompiled assets](https://github.com/elixir-nx/hnswlib/releases/tag/v0.1.0) that exist now are all using the old naming scheme.

🙏

**Comment by cocoa-xu** [comment]
Hi @amokan, thanks for mentioning this. I'll create a PR to address it!
