### ISSUE TITLE
/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by cocoa-xu** [elixir-nx/hnswlib#9]
I'll create a PR that tries to compile it with manylinux2014 so that we don't have to enforce users to use a newer version of `glibcxx`.

**Comment by jeregrine** [comment]
I ran into this issue with the cuda livebook dockerfile:

Failed to load nif: {:load_failed, ~c"Failed to load NIF library: '/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/livebook/.cache/mix/installs/elixir-1.15.7-erts-14.1.1/59959651cc70bf494edc9bd4cb70e408/_build/dev/lib/hnswlib/priv/hnswlib_nif.so)'"}
